<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-04-15 at 23:05:22.
 */
require_once (__DIR__) . '/../Calculator.php';

class CalculatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Calculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Calculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (1, 3) == 4.
     *
     * @covers Calculator::add
     */
    public function testAdd() {
        $this->assertEquals(
                4, $this->object->add(1, 3)
        );
    }

    /**
     * Generated from @assert (1, 3) == -2.
     *
     * @covers Calculator::sub
     */
    public function testSub() {
        $this->assertEquals(
                -2, $this->object->sub(1, 3)
        );
    }

    /**
     * Generated from @assert (5, 2) == 2.5.
     *
     * @covers Calculator::ratio
     */
    public function testRatio() {
        $this->assertEquals(
                2.5, $this->object->ratio(5, 2)
        );
    }

    /**
     * Generated from @assert (3.5, 2) == 1.75.
     *
     * @covers Calculator::ratio
     */
    public function testRatio2() {
        $this->assertEquals(
                1.75, $this->object->ratio(3.5, 2)
        );
    }

}
